/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) static_solver_position_boundary_cost_y_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[23] = {19, 1, 0, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* static_solver_position_boundary_cost_y_e_fun:(i0[19],i1[],i2[])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][13] : 0;
  a1=2.;
  a2=arg[0]? arg[0][3] : 0;
  a3=casadi_sq(a2);
  a4=arg[0]? arg[0][4] : 0;
  a5=casadi_sq(a4);
  a3=(a3+a5);
  a3=(a1*a3);
  a5=1.;
  a3=(a3-a5);
  a6=6.3661977236758142e-06;
  a7=(a6*a3);
  a8=arg[0]? arg[0][7] : 0;
  a7=(a7*a8);
  a9=arg[0]? arg[0][5] : 0;
  a10=(a4*a9);
  a11=arg[0]? arg[0][6] : 0;
  a12=(a2*a11);
  a10=(a10+a12);
  a10=(a1*a10);
  a12=(a6*a10);
  a13=arg[0]? arg[0][8] : 0;
  a12=(a12*a13);
  a7=(a7+a12);
  a12=(a4*a11);
  a14=(a2*a9);
  a12=(a12-a14);
  a12=(a1*a12);
  a14=(a6*a12);
  a15=arg[0]? arg[0][9] : 0;
  a14=(a14*a15);
  a7=(a7+a14);
  a14=(a3*a7);
  a16=(a4*a9);
  a17=(a2*a11);
  a16=(a16-a17);
  a16=(a1*a16);
  a17=(a6*a16);
  a17=(a17*a8);
  a18=casadi_sq(a2);
  a19=casadi_sq(a9);
  a18=(a18+a19);
  a18=(a1*a18);
  a18=(a18-a5);
  a19=(a6*a18);
  a19=(a19*a13);
  a17=(a17+a19);
  a19=(a9*a11);
  a20=(a2*a4);
  a19=(a19+a20);
  a19=(a1*a19);
  a6=(a6*a19);
  a6=(a6*a15);
  a17=(a17+a6);
  a6=(a16*a17);
  a14=(a14+a6);
  a6=(a4*a11);
  a20=(a2*a9);
  a6=(a6+a20);
  a6=(a1*a6);
  a20=1.2732395447351628e-05;
  a21=(a20*a6);
  a21=(a21*a8);
  a9=(a9*a11);
  a4=(a2*a4);
  a9=(a9-a4);
  a9=(a1*a9);
  a4=(a20*a9);
  a4=(a4*a13);
  a21=(a21+a4);
  a2=casadi_sq(a2);
  a11=casadi_sq(a11);
  a2=(a2+a11);
  a1=(a1*a2);
  a1=(a1-a5);
  a20=(a20*a1);
  a20=(a20*a15);
  a21=(a21+a20);
  a21=(a21+a5);
  a6=(a6*a21);
  a14=(a14+a6);
  a6=casadi_sq(a14);
  a5=(a10*a7);
  a20=(a18*a17);
  a5=(a5+a20);
  a9=(a9*a21);
  a5=(a5+a9);
  a9=casadi_sq(a5);
  a6=(a6+a9);
  a7=(a12*a7);
  a17=(a19*a17);
  a7=(a7+a17);
  a1=(a1*a21);
  a7=(a7+a1);
  a1=casadi_sq(a7);
  a6=(a6+a1);
  a6=sqrt(a6);
  a1=(a14/a6);
  a1=(a0*a1);
  a21=arg[0]? arg[0][14] : 0;
  a17=casadi_sq(a14);
  a9=casadi_sq(a5);
  a17=(a17+a9);
  a9=casadi_sq(a7);
  a17=(a17+a9);
  a17=sqrt(a17);
  a9=(a14/a17);
  a9=(a21*a9);
  a1=(a1+a9);
  a9=arg[0]? arg[0][15] : 0;
  a20=casadi_sq(a14);
  a2=casadi_sq(a5);
  a20=(a20+a2);
  a2=casadi_sq(a7);
  a20=(a20+a2);
  a20=sqrt(a20);
  a2=(a14/a20);
  a2=(a9*a2);
  a1=(a1+a2);
  a1=(a1+a8);
  a1=(-a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=(a5/a6);
  a1=(a0*a1);
  a8=(a5/a17);
  a8=(a21*a8);
  a1=(a1+a8);
  a8=(a5/a20);
  a8=(a9*a8);
  a1=(a1+a8);
  a1=(a1+a13);
  a1=(-a1);
  if (res[0]!=0) res[0][1]=a1;
  a6=(a7/a6);
  a6=(a0*a6);
  a17=(a7/a17);
  a17=(a21*a17);
  a6=(a6+a17);
  a20=(a7/a20);
  a20=(a9*a20);
  a6=(a6+a20);
  a6=(a6+a15);
  a6=(-a6);
  if (res[0]!=0) res[0][2]=a6;
  a6=2.7999999999999997e-02;
  a15=(a6*a10);
  a20=(a0*a15);
  a17=casadi_sq(a14);
  a1=casadi_sq(a5);
  a17=(a17+a1);
  a1=casadi_sq(a7);
  a17=(a17+a1);
  a17=sqrt(a17);
  a1=(a7/a17);
  a20=(a20*a1);
  a13=(a6*a12);
  a8=(a0*a13);
  a2=(a5/a17);
  a8=(a8*a2);
  a20=(a20-a8);
  a8=-1.2250000000000000e-02;
  a11=(a8*a10);
  a4=2.1217559999999996e-02;
  a22=(a4*a18);
  a11=(a11+a22);
  a22=(a21*a11);
  a23=casadi_sq(a14);
  a24=casadi_sq(a5);
  a23=(a23+a24);
  a24=casadi_sq(a7);
  a23=(a23+a24);
  a23=sqrt(a23);
  a24=(a7/a23);
  a22=(a22*a24);
  a25=(a8*a12);
  a26=(a4*a19);
  a25=(a25+a26);
  a26=(a21*a25);
  a27=(a5/a23);
  a26=(a26*a27);
  a22=(a22-a26);
  a20=(a20+a22);
  a10=(a8*a10);
  a22=-2.1217559999999996e-02;
  a18=(a22*a18);
  a10=(a10+a18);
  a18=(a9*a10);
  a26=casadi_sq(a14);
  a28=casadi_sq(a5);
  a26=(a26+a28);
  a28=casadi_sq(a7);
  a26=(a26+a28);
  a26=sqrt(a26);
  a7=(a7/a26);
  a18=(a18*a7);
  a12=(a8*a12);
  a19=(a22*a19);
  a12=(a12+a19);
  a19=(a9*a12);
  a5=(a5/a26);
  a19=(a19*a5);
  a18=(a18-a19);
  a20=(a20+a18);
  a18=arg[0]? arg[0][10] : 0;
  a20=(a20+a18);
  a20=(-a20);
  if (res[0]!=0) res[0][3]=a20;
  a13=(a0*a13);
  a17=(a14/a17);
  a13=(a13*a17);
  a6=(a6*a3);
  a20=(a0*a6);
  a20=(a20*a1);
  a13=(a13-a20);
  a25=(a21*a25);
  a23=(a14/a23);
  a25=(a25*a23);
  a20=(a8*a3);
  a4=(a4*a16);
  a20=(a20+a4);
  a4=(a21*a20);
  a4=(a4*a24);
  a25=(a25-a4);
  a13=(a13+a25);
  a12=(a9*a12);
  a14=(a14/a26);
  a12=(a12*a14);
  a8=(a8*a3);
  a22=(a22*a16);
  a8=(a8+a22);
  a22=(a9*a8);
  a22=(a22*a7);
  a12=(a12-a22);
  a13=(a13+a12);
  a12=arg[0]? arg[0][11] : 0;
  a13=(a13+a12);
  a13=(-a13);
  if (res[0]!=0) res[0][4]=a13;
  a6=(a0*a6);
  a6=(a6*a2);
  a0=(a0*a15);
  a0=(a0*a17);
  a6=(a6-a0);
  a20=(a21*a20);
  a20=(a20*a27);
  a21=(a21*a11);
  a21=(a21*a23);
  a20=(a20-a21);
  a6=(a6+a20);
  a8=(a9*a8);
  a8=(a8*a5);
  a9=(a9*a10);
  a9=(a9*a14);
  a8=(a8-a9);
  a6=(a6+a8);
  a8=arg[0]? arg[0][12] : 0;
  a6=(a6+a8);
  a6=(-a6);
  if (res[0]!=0) res[0][5]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int static_solver_position_boundary_cost_y_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int static_solver_position_boundary_cost_y_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int static_solver_position_boundary_cost_y_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void static_solver_position_boundary_cost_y_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int static_solver_position_boundary_cost_y_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void static_solver_position_boundary_cost_y_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void static_solver_position_boundary_cost_y_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void static_solver_position_boundary_cost_y_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int static_solver_position_boundary_cost_y_e_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int static_solver_position_boundary_cost_y_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real static_solver_position_boundary_cost_y_e_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* static_solver_position_boundary_cost_y_e_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* static_solver_position_boundary_cost_y_e_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* static_solver_position_boundary_cost_y_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* static_solver_position_boundary_cost_y_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int static_solver_position_boundary_cost_y_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
